[package]
name = "drwa-attestation"
version = "0.0.0"
edition = "2024"
publish = false
authors = ["Dharitri <dev@dharitri.org>"]

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
workspace = true

[dependencies.drwa-common]
path = "../common"

[dev-dependencies.multiversx-sc-scenario]
workspace = true
features = ["wasmer-experimental"]
