// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           33
// Async Callback (empty):               1
// Total number of exported functions:  36

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_aggregator
    (
        init => init
        upgrade => upgrade
        setGovernanceReadAddress => set_governance_read_address
        clearGovernanceReadAddress => clear_governance_read_address
        submitOracleReading => submit_oracle_reading
        trySeal => try_seal
        forceSealAfterTimeout => force_seal_after_timeout
        acknowledgeDiscrepancy => acknowledge_discrepancy
        setQuorum => set_quorum
        setCoherenceWindows => set_coherence_windows
        registerOracle => register_oracle
        deregisterOracle => deregister_oracle
        isOracleAuthorized => is_oracle_authorized
        registerOracleForSource => register_oracle_for_source
        revokeOracleSource => revoke_oracle_source
        isOracleSourceAuthorized => is_oracle_source_authorized
        registerVerifier => register_verifier
        deregisterVerifier => deregister_verifier
        isVerifierAuthorized => is_verifier_authorized
        registerDevice => register_device
        registerDevicePublicKey => register_device_public_key
        deregisterDevice => deregister_device
        isDeviceRegistered => is_device_registered
        proposeOracleUpdate => propose_oracle_update
        acceptOracleUpdate => accept_oracle_update
        cancelExpiredProposal => cancel_expired_proposal
        getSealedEvent => get_sealed_event
        isSealed => is_sealed
        getGovernanceReadAddress => governance_read_address
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
