[package]
name = "drwa-common-test-harness"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
workspace = true

[dependencies.drwa-common]
path = ".."

[dev-dependencies.multiversx-sc-scenario]
workspace = true
features = ["wasmer-experimental"]
