// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           29
// Async Callback (empty):               1
// Total number of exported functions:  32

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    drwa_auth_admin
    (
        init => init
        upgrade => upgrade
        proposeUpdateCallerAddress => propose_update_caller_address
        proposeAddSigner => propose_add_signer
        proposeRemoveSigner => propose_remove_signer
        proposeReplaceSigner => propose_replace_signer
        proposeChangeQuorum => propose_change_quorum
        sign => sign
        unsign => unsign
        discardAction => discard_action
        performAction => perform_action
        getQuorum => quorum
        getProposalTtlRounds => proposal_ttl_rounds
        getNextActionId => next_action_id
        getAction => actions
        getActionProposer => action_proposer
        getActionCreatedRound => action_created_round
        getActionExpiryRound => action_expiry_round
        getActionApprovedAtRound => action_approved_at_round
        getActionTimelockRounds => action_timelock_rounds
        getActionApprovedAtTimestampSeconds => action_approved_at_timestamp_seconds
        getActionTimelockSeconds => action_timelock_seconds
        getAllSigners => signers
        getActionSigners => action_signers
        getStorageVersion => storage_version
        getSignerPendingActionIds => signer_pending_action_ids
        getPerformedActionIds => performed_action_ids
        getAuthorizedCaller => authorized_caller
        getAuthorizedCallerVersion => authorized_caller_version
        isEmergencyOverrideSupported => is_emergency_override_supported
        getEmergencyOverridePolicy => get_emergency_override_policy
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
