// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use drwa_common::{DrwaSyncEnvelope, DrwaTokenPolicy};
use multiversx_sc::proxy_imports::*;

pub struct DrwaPolicyRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for DrwaPolicyRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = DrwaPolicyRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        DrwaPolicyRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct DrwaPolicyRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> DrwaPolicyRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&governance)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> DrwaPolicyRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }

    pub fn set_token_policy<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<bool>,
        Arg2: ProxyArg<bool>,
        Arg3: ProxyArg<bool>,
        Arg4: ProxyArg<bool>,
        Arg5: ProxyArg<ManagedVec<Env::Api, ManagedBuffer<Env::Api>>>,
        Arg6: ProxyArg<ManagedVec<Env::Api, ManagedBuffer<Env::Api>>>,
        Arg7: ProxyArg<bool>,
        Arg8: ProxyArg<bool>,
    >(
        self,
        token_id: Arg0,
        drwa_enabled: Arg1,
        global_pause: Arg2,
        strict_auditor_mode: Arg3,
        metadata_protection_enabled: Arg4,
        allowed_investor_classes: Arg5,
        allowed_jurisdictions: Arg6,
        travel_rule_required: Arg7,
        sanctions_screening_enabled: Arg8,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setTokenPolicy")
            .argument(&token_id)
            .argument(&drwa_enabled)
            .argument(&global_pause)
            .argument(&strict_auditor_mode)
            .argument(&metadata_protection_enabled)
            .argument(&allowed_investor_classes)
            .argument(&allowed_jurisdictions)
            .argument(&travel_rule_required)
            .argument(&sanctions_screening_enabled)
            .original_result()
    }

    pub fn set_governance<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setGovernance")
            .argument(&governance)
            .original_result()
    }

    pub fn accept_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptGovernance")
            .original_result()
    }

    pub fn token_policy<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaTokenPolicy<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTokenPolicy")
            .argument(&token_id)
            .original_result()
    }

    pub fn deactivate_token_policy<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("deactivateTokenPolicy")
            .argument(&token_id)
            .original_result()
    }

    pub fn revoke_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeGovernance")
            .original_result()
    }

    pub fn token_policy_version<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTokenPolicyVersion")
            .argument(&token_id)
            .original_result()
    }

    pub fn governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGovernance")
            .original_result()
    }

    pub fn pending_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingGovernance")
            .original_result()
    }
}
