// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use crate::{AssetLegalCustodyPack, AssetRecord};
use drwa_common;
use drwa_common::DrwaSyncEnvelope;
use multiversx_sc::proxy_imports::*;

pub struct DrwaAssetManagerProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for DrwaAssetManagerProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = DrwaAssetManagerProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        DrwaAssetManagerProxyMethods { wrapped_tx: tx }
    }
}

pub struct DrwaAssetManagerProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> DrwaAssetManagerProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&governance)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> DrwaAssetManagerProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }

    pub fn register_asset<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
        carrier_type: Arg1,
        asset_class: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerAsset")
            .argument(&token_id)
            .argument(&carrier_type)
            .argument(&asset_class)
            .original_result()
    }

    pub fn attach_asset_legal_custody_pack<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedAddress<Env::Api>>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg6: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
        legal_pack_hash: Arg1,
        custody_attestation_hash: Arg2,
        insurance_ref_hash: Arg3,
        valuation_authority: Arg4,
        redemption_terms_hash: Arg5,
        asset_state_proof_hash: Arg6,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("attachAssetLegalCustodyPack")
            .argument(&token_id)
            .argument(&legal_pack_hash)
            .argument(&custody_attestation_hash)
            .argument(&insurance_ref_hash)
            .argument(&valuation_authority)
            .argument(&redemption_terms_hash)
            .argument(&asset_state_proof_hash)
            .original_result()
    }

    pub fn sync_holder_compliance<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg6: ProxyArg<u64>,
        Arg7: ProxyArg<bool>,
        Arg8: ProxyArg<bool>,
        Arg9: ProxyArg<bool>,
        Arg10: ProxyArg<u64>,
        Arg11: ProxyArg<bool>,
        Arg12: ProxyArg<bool>,
        Arg13: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg14: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg15: ProxyArg<u32>,
    >(
        self,
        token_id: Arg0,
        holder: Arg1,
        kyc_status: Arg2,
        aml_status: Arg3,
        investor_class: Arg4,
        jurisdiction_code: Arg5,
        expiry_round: Arg6,
        transfer_locked: Arg7,
        receive_locked: Arg8,
        auditor_authorized: Arg9,
        lock_until_round: Arg10,
        travel_rule_attested: Arg11,
        sanctions_cleared: Arg12,
        sanctions_screening_cid: Arg13,
        ubo_parent_entity: Arg14,
        ownership_pct: Arg15,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("syncHolderCompliance")
            .argument(&token_id)
            .argument(&holder)
            .argument(&kyc_status)
            .argument(&aml_status)
            .argument(&investor_class)
            .argument(&jurisdiction_code)
            .argument(&expiry_round)
            .argument(&transfer_locked)
            .argument(&receive_locked)
            .argument(&auditor_authorized)
            .argument(&lock_until_round)
            .argument(&travel_rule_attested)
            .argument(&sanctions_cleared)
            .argument(&sanctions_screening_cid)
            .argument(&ubo_parent_entity)
            .argument(&ownership_pct)
            .original_result()
    }

    pub fn set_policy_registry_address<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        policy_registry: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setPolicyRegistryAddress")
            .argument(&policy_registry)
            .original_result()
    }

    pub fn update_asset<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
        carrier_type: Arg1,
        asset_class: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateAsset")
            .argument(&token_id)
            .argument(&carrier_type)
            .argument(&asset_class)
            .original_result()
    }

    pub fn get_holder_mirror<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        token_id: Arg0,
        holder: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, drwa_common::DrwaHolderMirror<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getHolderMirror")
            .argument(&token_id)
            .argument(&holder)
            .original_result()
    }

    pub fn revoke_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeGovernance")
            .original_result()
    }

    pub fn set_governance<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setGovernance")
            .argument(&governance)
            .original_result()
    }

    pub fn accept_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptGovernance")
            .original_result()
    }

    pub fn asset<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, AssetRecord<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAsset")
            .argument(&token_id)
            .original_result()
    }

    pub fn asset_legal_custody_pack<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, AssetLegalCustodyPack<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAssetLegalCustodyPack")
            .argument(&token_id)
            .original_result()
    }

    pub fn governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGovernance")
            .original_result()
    }

    pub fn policy_registry_address(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPolicyRegistryAddress")
            .original_result()
    }

    pub fn pending_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingGovernance")
            .original_result()
    }
}
