[package]
name = "drwa-common"
version = "0.0.0"
edition = "2024"
publish = false
authors = ["Dharitri <dev@dharitri.org>"]

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
workspace = true

[dev-dependencies.multiversx-sc-scenario]
workspace = true
features = ["wasmer-experimental"]

[dev-dependencies.drwa-policy-registry]
path = "../policy-registry"

[dev-dependencies.drwa-identity-registry]
path = "../identity-registry"

[dev-dependencies.drwa-asset-manager]
path = "../asset-manager"

[dev-dependencies.drwa-attestation]
path = "../attestation"
