// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           26
// Async Callback (empty):               1
// Total number of exported functions:  29

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    drwa_asset_manager
    (
        init => init
        upgrade => upgrade
        setPolicyRegistryAddress => set_policy_registry_address
        registerAsset => register_asset
        attachAssetLegalCustodyPack => attach_asset_legal_custody_pack
        syncHolderCompliance => sync_holder_compliance
        updateAsset => update_asset
        initiateWindDown => initiate_wind_down
        completeWindDown => complete_wind_down
        cancelWindDown => cancel_wind_down
        isWindDownInitiated => is_wind_down_initiated
        getWindDownStatusCode => get_wind_down_status_code
        getWindDownStatusRound => get_wind_down_status_round
        getWindDownEvidenceCid => get_wind_down_evidence_cid
        getAsset => asset
        getWindDownStatusStorage => wind_down_status
        getWindDownStatusRoundStorage => wind_down_status_round
        getWindDownEvidenceCidStorage => wind_down_evidence_cid
        getAssetLegalCustodyPack => asset_legal_custody_pack
        getHolderMirror => get_holder_mirror
        getHolderPolicyVersionEvaluated => holder_policy_version_evaluated
        getPolicyRegistryAddress => policy_registry_address
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        revokeGovernance => revoke_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
