[package]
name = "mrv-aggregator"
version = "0.0.0"
edition = "2024"
publish = false
authors = ["Dharitri <dev@dharitri.org>"]

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
workspace = true

[dependencies.mrv-common]
path = "../common"

[dev-dependencies.multiversx-sc-scenario]
workspace = true
features = ["wasmer-experimental"]

[dev-dependencies.mrv-governance]
path = "../governance"

[dev-dependencies.ed25519-dalek]
version = "2.2.0"
